### PR TITLE
Image rotation and running unit tests from the command-line

### PR DESCRIPTION
**Pull request by ewchow**
Hello @ankitrohatgi, hope you are well!

I have two main updates in this PR:
- Added image rotation 
- Added ability to run unit tests from the command-line

Let me know your thoughts, happy to make additional changes.

-----

### Image rotation

Two new buttons have been added next to the zoom controls in the top toolbar - one for rotating 90° counter-clockwise, one for rotating 90° clockwise; as seen here:

image

@billdenney and I thought this would compliment the existing set of image manipulation features well.

This rotation is achieved by rotating the appropriate canvases with 4 pre-defined transformation matrices. This can be updated to allow rotation to degrees that are not a multiple of 90°, but currently only multiples of 90° are supported.

Some notable points:
- Axis calibration, data, and measurement points captured on a rotated image are stored as if they were not rotated
- Keyboard adjustment of axis calibration, data, and measurement points work in the expected orientation
- Image rotations and zoom levels work together
- Zoomed image (top-right box) have been updated to work with rotations
- Image cropping (including undo and redo actions) has been updated to work with rotations
- Rotations are saved for PDFs by page
- Rotations are loaded for PDFs

Known short-comings:
- Rotations are currently not stored for standalone images
- Point labels are currently not rotated, this will require some additional code to rotate the canvas and draw the label in the correct location

### Running unit tests from the command-line

While I was adding unit tests for image rotation, I thought it would be nice to be able to run the unit tests via the command-line. This would enable git pre-commit/pre-push hooks to run unit tests down the road as well. (And perhaps along with code formatting.)

I installed [Karma](https://karma-runner.github.io/) as a dev dependency. You've probably hear of it; it's a test runner that can spin up browsers, watch for changes, and run tests in them.

I configured Karma to run tests and exit instead of watching for changes, but that can be changed with a few command-line options. By default, I'm having it run on Headless Chrome. Launchers for Chrome, Firefox, and Edge are also installed (these are not headless). I added usage details at the updated [DEVELOPER_GUIDELINES.md](https://github.com/ewchow/WebPlotDigitizer/blob/feature/add-image-rotation/DEVELOPER_GUIDELINES.md#unit-tests).

Karma can also run tests on Electron, but required the `electron` package to be installed in `app` as well. I didn't want to duplicate a somewhat large package, so I did not move forward with it.

I also added a convenience shortcut to `package.json` so unit tests can now be run in the command-line via `npm test` 🙂

### CODE REVIEW

**Comment by ankitrohatgi** [comment]
Hi Eric, I'll take a closer look soon. 

For now, I was curious about the use case for this addition and was wondering if you could provide some more info/examples. Right now I'm thinking that rotation is something one would do need to do only once for an image and not frequently while performing analysis (zooming is quite frequent). If it's only an operation that needs to happen once then adding it as an image editing operation (like crop) would be a lot simpler code change.

**Comment by billdenney** [comment]
Hi @ankitrohatgi, I can help with the use case.

I relatively often read .pdf files (i.e. journal articles) where individual figures may be rotated to be landscape and the rest of the pages are portrait.  (I can't immediately find one that I can share due to copyright issues.  I just checked about 10 articles in the PLOS journal family and didn't see one.  It's not the most common thing, either.)

The page may not have a .pdf flag that makes it landscape.  In other words, the page content may be best read as landscape but the way that the .pdf file is setup, it may tell the .pdf reader that the page is portrait.  This portrait/landscape limitation is a limitation within most if not all TeX-generated documents: https://tex.stackexchange.com/questions/337/how-to-change-certain-pages-into-landscape-portrait-mode (to be clear as you'll see in the Stack Exchange link, it is possible, but I don't often see it actually done).

You're right that most often it is only needed once per image/page, but I would guess editing the .pdf file itself would be difficult within WPD.  And, to edit the .pdf outside of WPD is still usually difficult (and sometimes very difficult if some of the pdf archival security flags are set).

On very rare occasions, I have seen a .pdf document with a landscape figure filling all of column 1 and a portrait figure as part of column 2.  In that case, more than one rotation may be desired.  (Page 4 of this paper has something a bit like what I just described with a table though not a figure: https://www.jbc.org/article/S0021-9258(22)00231-9/pdf)

If helpful, I can keep an eye out for more example files.

**Comment by ankitrohatgi** [comment]
Hi @billdenney! I think I understand your workflow now, thanks for providing this detail. I wasn't thinking of multi page PDF documents earlier. Given what you just said, @ewchow 's solution definitely makes a lot of sense. 

I'll take a better look at this PR in the next few days and get back.

**Comment by ewchow** [comment]
Thanks for the use case, @billdenney! I got caught up in the details and forgot to mention the reasoning.

And thanks for looking into this @ankitrohatgi, let me know if you have questions or concerns about the commits.

**Comment by ankitrohatgi** [comment]
I took a pass at reviewing the code changes and also trying the new features. No major comments, everything looks pretty good, just need some more time to review :)

**Comment by ankitrohatgi** [comment]
Hi @ewchow - I don't see any major issues, I'm going to go ahead and merge this :) 

Thanks for adding Karma - definitely useful!

**Comment by ewchow** [comment]
Glad to hear that! Thanks for looking over the commits @ankitrohatgi. I'll keep an eye out as well, but if there are bugs that could be related to this PR don't hesitate to reach out.

**Pull request merged**
