### PR TITLE
Run completely client-side and offline (where supported)

### PR DESCRIPTION
**Pull request by JakeOShannessy**
This pull request allows the page to operate without calling back to the server (i.e. the php scripts). On browsers that have shipped service workers it will also work completely offline.

This is a patch I've been using because I need to work offline often. Most of the changes below are the addition of a manifest, service worker, and some larger icons. The only changes to code are feature tested, so if a browser doesn't support the download attribute then the code will revert to calling the php scripts as it does now. In environments that don't support either of these features then this patch should not make a difference.

I haven't actually been able to test the lack of the download attribute because I can't run IE11 or Safari.

I had similar problems as in #97 so thought I would submit the patch.

### CODE REVIEW

**Comment by JakeOShannessy** [comment]
Regarding #55, I believe this methodology (which does not pack the data into a href) allows for up to 500 MiB in past versions of Chrome and Firefox, but are much higher in stable versions (multi-gigabyte).

In Chrom (quoted from [https://bugs.chromium.org/p/chromium/issues/detail?id=375297](https://bugs.chromium.org/p/chromium/issues/detail?id=375297));

> In-memory quota:
> * 2GB if system is x64 and NOT ChromeOS or Android
> * Total RAM amount / 5;
> 
> Disk quota:
> * Disk size / 2 if ChromeOS (user partition disk size)
> * Disk size / 20 if Android
> * Disk size / 10 otherwise.

**Comment by ankitrohatgi** [comment]
Thanks a lot for putting together. I'll take a look at this today evening or tomorrow. It's been a couple of years since I looked into this issue.

**Comment by ankitrohatgi** [comment]
Hello Jake,

Can you explain what the role of the service worker is in this (sw.js)? Is that needed for the download patch? Service workers only run over HTTPS so if that is necessary then I will have to wait to merge this until version 4 is ready. Version 4 will be hosted with HTTPS on a different server.

I haven't tried out this yet.

Thanks,
Ankit

**Comment by JakeOShannessy** [comment]
The service worker isn't needed at all for the download patch (I probably should have split them into separate pull requests). The sole purpose of the service worker is to cache the the assets for offline use. You're right in that service workers only work over HTTPS, but if you try and serve them over HTTP it will simply log that it can't register the service worker, so it won't affect the normal operation of the site.

That's a core aim behind both of these actually, that where they are not supported they make no difference. If it is hosted elsewhere with HTTPS the service worker will just run without modification.

I was looking at the Version 4 code before, is that server side code just fulfilling the same role as PHP now? I.e. all of the functionality remains client side and the server is just used for downloads?

**Comment by ankitrohatgi** [comment]
Thanks for the clarification. I will go through your PR in more detail this weekend.

Version 4 is the next major update intended to address many user requests and some objectives of my own. Eventually, I plan on revisiting almost every bit of code in the current tool. I have to start somewhere so for now I am just replacing the PHP scripts and serving static files using the Go backend. I will keep adding more stuff as time goes on in 4.x releases.

**Comment by JakeOShannessy** [comment]
Ok great, so the methods in this patch will still work with Version 4.

**Comment by ankitrohatgi** [comment]
Hi Jake,
I have included your download specific recommendation in the version4 branch. I had changed that area of code earlier so a direct merge would have been difficult. I'll look into service workers next.
Thanks!

**Comment by dam90** [comment]
For those interested:

My solution for offline WebPlotDigitizer is a small (~20MB) docker container built on GitLab CI/CD: https://gitlab.com/dam90/plot-digitizer-ci

I haven't set it up to build automatically when this project is updated, but that would be easy.

The only asset it fails to load (when on an air-gapped network) is google fonts, which doesn't appear to affect the operation of the tool.

**Pull request closed without merging**
