### PR TITLE
Events and more metadata

### PR DESCRIPTION
**Pull request by ewchow**
Hey @ankitrohatgi,

Hope the new year is treating you well so far.

These commits contain a new event system, new metadata support for axes, data sets, and data points, and additional unit tests. The intent behind these infrastructures are that they won't be directly used via WPD's UI, but rather used via the user scripts infrastructure. WPD can certainly make use of these in the future as well, should the need arise.

Here's a quick summary of the commits:
- Event system that allows for registering handlers when axes, data sets, or data points are added, deleted, or selected
    - Built on top of native custom events
- Support for adding metadata on axes and data sets
    - Metadata on axes and data sets for describing graph information such as units
- Support for adding metadata on data points
    - Expands upon existing infrastructure on data point metadata (i.e. bar axes for labels)
    - Metadata on points for describing any arbitrary pieces of information, such as values or labels in image axes

If you're okay with these changes, I'll add some documentation to describe the event and metadata infrastructure for user scripts.

### CODE REVIEW

**Comment by ankitrohatgi** [comment]
nice! I'll take a closer look over the weekend :)

**Comment by ankitrohatgi** [comment]
Sorry for the delay on this - changes look good in general. I don't have any concerns, just need a bit more time to review (~1-2 days)

**Review by ankitrohatgi — APPROVED** [review]
LGTM :)

**Comment by ewchow** [comment]
Awesome. Thanks! I'll write up some documentation later this week.

**Pull request merged**
